NAME = megaphone

SRC = megaphone.c

CXX = c++;
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

ALL : $(NAME)

$(NAME) : $(SRC)
$(CXX) $(CXXFLAGS) $(SRC) -o (NAME)

clean:

rm -f $(NAME)

fclean: clean

re: fclean all;

.PHONY: all clean fclean re 


